import type { Metadata } from 'next';
import { Raleway, Roboto } from 'next/font/google';

import Header from '@/components/header';

import './globals.css';

const raleway = Raleway({ subsets: ['latin'], variable: '--heading-font' });
const roboto = Roboto({
  subsets: ['latin'],
  variable: '--body-font',
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${roboto.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
